sheets:
  Character:
    status:
      singular: Status
      plural: Statuses
    quality:
      singular: Quality
      plural: Qualities
    edge-action:
      singular: Edge Action
      plural: Edge Actions
  Magic:
    spell:
      singular: Spell
      plural: Spells