sheets:
  Character:
    status:
      singular: Status
      plural: Statuses
    quality:
      singular: Quality
      plural: Qualities
  Magic:
    spell:
      singular: Spell
      plural: Spells